version: "3.8"
services:
  app:
    build:
      context: .
    links:
      - postgres
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    environment:
      - FLASK_APP=app.py
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - postgres:/var/lib/postgresql/data
      - ./db/init.sql/:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  postgres:
    driver: local